#! /bin/sh

# Set up remote if it doesn't exist.
git config remote.abbot-api-messages.url >&- || git remote add abbot-api-messages https://github.com/aseriousbiz/abbot-api-messages.git

# Push changes back to https://github.com/aseriousbiz/abbot-api-messages

git subtree push --prefix src/Abbot.Messages abbot-api-messages main
