#!/bin/sh -eu

{ set +x; } 2>/dev/null
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

OS="Mac"
if [[ -e "/c/" ]]; then
	OS="Windows"
fi

rm -rf ./publish
script/build -r -p